data_train: './market1500/train.csv'
data_val: './market1500/val.csv'
data_test: './market1500/test.csv'
label_name: ['different', 'same']
save_model_path: './market1500/models'
checkpoint_path: './market1500/model_checkpoint'
epochs: 100
batch_size: 32
learning_rate: 1e-4
lr_patience: 5
early_stopping_patience: 10